[[plugins]]
repo =  'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = "release/rpc"

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"

[[plugins]]
repo = 'pechorin/any-jump.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'lambdalisue/gina.vim'

#=========================================================="
#color theme
[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'mangeshrex/uwu.vim'

